### PR TITLE
Fix: minEnclosingCircle

### PR DESCRIPTION
**Pull request by rainyl**
fix: #284 #282

### CODE REVIEW

**Comment by rainyl** [comment]
> Unable to strip library '.../build/app/intermediates/merged_native_libs/release/out/lib/armeabi-v7a/libdartcv.so' due to missing strip tool for ABI 'ARMEABI_V7A'. Packaging it as is.

It's because the ndk used to strip not exists, maybe we should specify the ndk version in `opencv_core/android/build.gradle`

**Comment by rainyl** [comment]
`android.ndkVersion` is unavailable in `android/build.gradle` when building the example... I think it's a bug of Flutter or gradle.

**Comment by abdelaziz-mahdy** [comment]
wow thats a very nice reduction of the package size

**Comment by abdelaziz-mahdy** [comment]
btw do you know how to reduce windows and linux package sizes too? specially for the `opencv_dart` one like a minimal version of ffmpeg

**Comment by rainyl** [comment]
> btw do you know how to reduce windows and linux package sizes too? specially for the `opencv_dart` one like a minimal version of ffmpeg

FFMPEG for windows and linux are downloaded from https://github.com/rainyl/FFmpeg-Builds/releases , so it's necessary to configure the build flags properly if we want to reduce the size of ffmpeg.

**Pull request merged**
