### PR TITLE
Improve performance and optimize memory

### LINKED ISSUE #64: Memory consumption
**Describe the bug**
memory is not being freed correctly i think
this is my example https://github.com/abdelaziz-mahdy/face_grouping 

try to pick a dir with images in it it should extract the faces in it, 

from the devtools the memory should be 100mb 
image

but in activity monitor its 2 gb
image

**Expected behavior**
i think the memory should be the same as devtools and since they are not the same i think there is a problem with how the c part frees the memory 

**Desktop (please complete the following information):**
 - OS: Macbook pro m2

**Smartphone (please complete the following information):**
 - Device: Macos
 - ABI Version arm64

**Additional context**

### PR DESCRIPTION
**Pull request by rainyl**
Reduce the consumption, improve performance

- [x] Optimize the use of Arenas
- [x] Add dispose() to all classes with native pointer
- [x] Add detach to the constructors with native pointer

### CODE REVIEW

**Comment by rainyl** [comment]
Ready to merge.

Note:
- Wrapper classes with large native resources, users now can free them manually with `dispose()` to free native resources, but note that the dart instances will still be available, users have to ensure not to access them if disposed, dart instances are small and believe dart VM/GC to manage them.

Example:

```dart

import 'package:opencv_dart/opencv_dart.dart' as cv;

void main() {
  const counts = 10000;
  final mat = cv.Mat.zeros(1000, 1000, cv.MatType.CV_8UC3);
  final sw = Stopwatch()..start();
  for (var count = 0; count < counts; count++) {
    final mat1 = cv.cvtColor(mat, cv.COLOR_BGR2YCrCb);
    // manually dispose will reduce the memory consumption
    mat1.dispose();
  }
  sw.stop();
  print(
      "All: ${sw.elapsedMicroseconds}μs, counts: $counts, per: ${sw.elapsedMicroseconds / counts} μs");
}

```

Without `mat1.dispose()`, memory: `~18G`
```bash
All: 5527358μs, counts: 10000, per: 552.7358 μs
```

With `mat1.dispose()`, memory: `~240M`
```bash
All: 7263633μs, counts: 10000, per: 726.3633 μs
```

**Comment by rainyl** [comment]
> package user will have to manage the object?



> > Ready to merge.
> > Note:
> > 
> > * Wrapper classes with large native resources, users now can free them manually with `dispose()` to free native resources, but note that the dart instances will still be available, users have to ensure not to access them if disposed, dart instances are small and believe dart VM/GC to manage them.
> > 
> > Example:
> > ```dart
> > import 'package:opencv_dart/opencv_dart.dart' as cv;
> > 
> > void main() {
> >   const counts = 10000;
> >   final mat = cv.Mat.zeros(1000, 1000, cv.MatType.CV_8UC3);
> >   final sw = Stopwatch()..start();
> >   for (var count = 0; count < counts; count++) {
> >     final mat1 = cv.cvtColor(mat, cv.COLOR_BGR2YCrCb);
> >     // manually dispose will reduce the memory consumption
> >     mat1.dispose();
> >   }
> >   sw.stop();
> >   print(
> >       "All: ${sw.elapsedMicroseconds}μs, counts: $counts, per: ${sw.elapsedMicroseconds / counts} μs");
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Without `mat1.dispose()`, peak memory: `~18G`
> > ```shell
> > All: 5527358μs, counts: 10000, per: 552.7358 μs
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > With `mat1.dispose()`, peak memory: `~240M`
> > ```shell
> > All: 7263633μs, counts: 10000, per: 726.3633 μs
> > ```
> 
> Does this mean the package user will have to manage the object? I another way do I have to dispose every native asset I use?

Not necessary, the above test is for dart, I didn't test in Flutter but Flutter will trigger GC more frequently than pure dart, so it tends to rely on GC to free, BUT, if users can know that the APP will process large images (e.g., 3840*2160*3), it's recommend to dispose manually.

Anyway, this PR just provides a potential to manage native resources more efficiently according to the weakness of the GC of dart VM, but not necessary.

**Comment by abdelaziz-mahdy** [comment]
Oh got it , so GC works too but if needed manual mode can be used for optimization

**Comment by rainyl** [comment]
> Oh got it , so GC works too but if needed manual mode can be used for optimization 

bingo!

**Pull request merged**
