### PR TITLE
Contrib async

### PR DESCRIPTION
**Pull request by abdelaziz-mahdy**
fix https://github.com/rainyl/opencv_dart/issues/124
> * [x]  C wrappers
> * [x]  dart bindings
> * [x]  tests

### CODE REVIEW

**Comment by abdelaziz-mahdy** [comment]
i dont think this is my best work, but i got lost since it different than the ones before it , so let me know if there is something that is a problem and needs to be fixed 

hopefully it should be all good

**Comment by rainyl** [comment]
> i dont think this is my best work, but i got lost since it different than the ones before it , so let me know if there is something that is a problem and needs to be fixed
> 
> hopefully it should be all good

Great, I will review it.

**Comment by rainyl** [comment]
I think get/set properties are actually unnecessary to be asynchorous, in my test, it will be a little slower than synchorous calls, and getter/setter usually pass primitive types like int and double, it's fast enough to not block the main thread.

So, I am going to delete all async getter/setter, what do you think?

**Review by rainyl — APPROVED** [review]
Ready for merging

**Comment by abdelaziz-mahdy** [comment]
> I think get/set properties are actually unnecessary to be asynchronous, in my test, it will be a little slower than synchronous calls, and getter/setter usually pass primitive types like int and double, it's fast enough to not block the main thread.
> 
> So, I am going to delete all async getter/setter, what do you think? 

I do agree that the overhead of running an isolate is not worth it.

**Pull request merged**
