### PR TITLE
Async Impl

### PR DESCRIPTION
**Pull request by rainyl**
<details>
<summary>Tasks</summary>

- [x] TODO: new library or mix to current?
- [x] add extra parameter `callback` to existed functions or add new functions? `new functions`, e.g., `CvStatus Mat_New_Async(MatCallback callback);` 
- [x] modules
  - [x] core
  - [x] calib3d
  - [x] contrib
  - [x] dnn
  - [x] features2d
  - [x] ~~gapi~~ TOD: too much works, add in the future
  - [x] ~~highgui~~
  - [x] imgproc
  - [x] imgcodecs
  - [x] objdetect
  - [x] photo
  - [x] stitching
  - [x] svd
  - [x] video
- [x] ~~bump opencv.full to 4.10.0+3~~

</details>

### CODE REVIEW

**Comment by rainyl** [comment]
So it works, but just need to rewrite nearly every API.

https://github.com/rainyl/opencv_dart/blob/03ee7e659a294cf28031ad4b76e02b0724ca0b75/example/lib/main.dart#L46-L53

async_example

**Comment by abdelaziz-mahdy** [comment]
i just saw it, i will retry to implement what i can and open a pr to this pr branch, can we spilt the modules so i handle some and you handle some to avoid we both implementing the same things?

**Comment by rainyl** [comment]
> i just saw it, i will try to implement what i can and open a pr to this pr branch, can we spilt the modules so i handle some and you handle some to avoid we both implementing the same things?

Sure, just create a new branch from async branch

> also whats the easiest module i can follow as a reference since this pr has the alot of changes, so an easy module to follow will be the best option

For now I just implemented calib3d and imgcodecs, I think imgcodecs is the easiest, just several API in it, but remember to take a loot at core/types.h, in which many basic definitions inside it.

**Comment by rainyl** [comment]
@abdelaziz-mahdy I have added async version of SVD, hope you are not doing the same module, may I ask which module are you working (or planning working) on?

**Comment by abdelaziz-mahdy** [comment]
I think dnn or objdetect, and if I faced any problem will let you know

**Comment by abdelaziz-mahdy** [comment]
can i ask why is this removed?https://github.com/rainyl/opencv_dart/pull/101/commits/b077b4a63ae6a9999a86557afda9e994848c4f4f i thought it will make it easier on us.

**Comment by rainyl** [comment]
> can i ask why is this removed?[b077b4a](https://github.com/rainyl/opencv_dart/commit/b077b4a63ae6a9999a86557afda9e994848c4f4f) i thought it will make it easier on us.

It's duplicate, https://github.com/rainyl/opencv_dart/blob/b077b4a63ae6a9999a86557afda9e994848c4f4f/lib/src/core/base.dart#L203-L207

**Comment by abdelaziz-mahdy** [comment]
> > can i ask why is this removed?[b077b4a](https://github.com/rainyl/opencv_dart/commit/b077b4a63ae6a9999a86557afda9e994848c4f4f) i thought it will make it easier on us.
> 
> It's duplicated,
> 
> https://github.com/rainyl/opencv_dart/blob/b077b4a63ae6a9999a86557afda9e994848c4f4f/lib/src/core/base.dart#L203-L207

very weird since i couldnt find it, maybe it was added in another commit, peace

**Comment by rainyl** [comment]
@abdelaziz-mahdy I think it's time to merge, thanks for your efforts!

**Comment by abdelaziz-mahdy** [comment]
> @abdelaziz-mahdy I think it's time to merge, thanks for your efforts!

Thank you for everything 💖

**Pull request merged**
