### PR TITLE
make file auto clone

### PR DESCRIPTION
**Pull request by abdelaziz-mahdy**
the make file will auto clone repo, before generating now since i saw you working on https://github.com/rainyl/opencv_dart/pull/299

### CODE REVIEW

**Comment by rainyl** [comment]
> the make file will auto clone repo, before generating now since i saw you working on #299

Yes I have implemented the dart code, but havn't finished the tests, you can work on it if you are willing to. :)

And for the makefile, it seems you are cloning the `rainyl/dartcv.git` and moving it to `packages/dartcv/src`, why don't you use the submodule commands? I mean

```terminal
# clone the repo and submodule
git clone https://github.com/rainyl/opencv_dart.git --recursive

# if you forgot --recursive during the cloning
git submodule update --init --recursive

# update to the latest commit of the submodule
git submodule update --remote
```

Therefore, I think if we want to simplify the above steps, just let `make submodule_update` to run `git submodule update --init --recursive` if the directory `packages/dartcv/src` is empty, else run `git submodule update --remote`, what do you think?

**Comment by abdelaziz-mahdy** [comment]
Well, I didn't notice at first that these were submodules, so I updated the Makefile to make it work as you mentioned. Let me know what you think. (I think this is safer since anyone who wants to contribute can just run the make command.)

**Comment by rainyl** [comment]
> Let me know what you think. (I think this is safer since anyone who wants to contribute can just run the make command.)

Sorry for my misleading 😢 . Agree it is safer, just do it~

**Comment by abdelaziz-mahdy** [comment]
> > Let me know what you think. (I think this is safer since anyone who wants to contribute can just run the make command.)
> 
> Sorry for my misleading 😢 . Agree it is safer, just do it~

I already did 😅, and looks like it works correctly

**Review by rainyl — APPROVED** [review]

**Comment by rainyl** [comment]
@abdelaziz-mahdy Merged, thanks～

**Pull request merged**
