### PR TITLE
Run on emulator (ci)

### PR DESCRIPTION
**Pull request by abdelaziz-mahdy**
a ci to test on emulator, to make sure the problem is not only on my machine and to make sure it works for other people too

### CODE REVIEW

**Comment by abdelaziz-mahdy** [comment]
ios failed same as my case, which is weird since flutter should auto run pod install :), android simulator failed to run, but i think android doesnt have a problem so we can ignore it

**Comment by rainyl** [comment]
thanks,i will test it later :)

**Comment by rainyl** [comment]
Well, now it success, maybe you forgot to  install build dependencies?

**Comment by abdelaziz-mahdy** [comment]
> Well, now it success, maybe you forgot to  install build dependencies?

The build dep are there, since it worked when I ran pod install (the build worked)

**Comment by rainyl** [comment]
> But setting the arch looks like it works, still if a universal framework can be achieved without increasing the size, well that will be the best option

Absolutely agree.

> dont know if its enabled or not, but i think that will be easier for future development? (note i dont understand it fully but looks like its the general option for our case) but does opencv build support it is the real question i cant figure out

I will take a look at it.

**Comment by rainyl** [comment]
@abdelaziz-mahdy I have published [v1.0.6](https://pub.dev/packages/opencv_dart/versions/1.0.6) with universal framework supported, could you please test whether it works on your devices?

**Comment by abdelaziz-mahdy** [comment]
> @abdelaziz-mahdy I have published [v1.0.6](https://pub.dev/packages/opencv_dart/versions/1.0.6) with universal framework supported, could you please test whether it works on your devices?

i failed to test due to https://github.com/rainyl/opencv_dart/issues/86 will wait for a fix then try again

**Comment by abdelaziz-mahdy** [comment]
i dont think this is needed anymore, reopen if its needed

**Comment by rainyl** [comment]
😺

**Comment by abdelaziz-mahdy** [comment]
> 😺

i love cats, but i didnt understand it in this context 😂

**Comment by rainyl** [comment]
hhhhh, just same as 😃 but a cat version.

**Pull request closed without merging**
