### PR TITLE
logging interface

### PR DESCRIPTION
**Pull request by abdelaziz-mahdy**
implementing logging interface fixing https://github.com/rainyl/opencv_dart/issues/173 

sync and async interfaces and test cases

### CODE REVIEW

**Comment by abdelaziz-mahdy** [comment]
i dont think getLogTagLevel or stuff related to tags is needed, but will leave it since it may be needed in specific use cases that i dont know

**Comment by rainyl** [comment]
Actually I think it's not necessary to add async version, getting and setting log level are fast enough. In my test, allocate and free memories have extra cost that will damage the performance.

**Comment by abdelaziz-mahdy** [comment]
> Actually I think it's not necessary to add async version, getting and setting log level are fast enough. In my test, allocate and free memories have extra cost that will damage the performance.

i thought that too, but i saw openCvVersionAsync so i followed it to match the sync async for all

**Comment by abdelaziz-mahdy** [comment]
well well here i go will delete the async for logging and the version stuff

**Comment by abdelaziz-mahdy** [comment]
done, but i think test will fail again.

**Comment by rainyl** [comment]
> done, but i think test will fail again.

Ok, I will test and fix it.

**Comment by rainyl** [comment]
@abdelaziz-mahdy 
I don't know why too, maybe the tag is not actually registered or available between different calls.

https://github.com/opencv/opencv/blob/eab21b61067385515c77783608f8c374bfe131c6/modules/core/src/logger.cpp#L146-L167

I searched in the repo of opencv and it seems the two API are not actually used. So, I think it's fine to remove setLogTagLevel and getLogTagLevel.

**Comment by abdelaziz-mahdy** [comment]
done, i think we can merge after ci is successful

**Review by rainyl — APPROVED** [review]

**Comment by rainyl** [comment]
@abdelaziz-mahdy Merged, thanks for your contribution!

**Pull request merged**
